# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: wikiful_development
  encoding: unicode
  user: wikiful
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: sqlite3
  database: wikiful_test
  encoding: unicode
  user: wikiful
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: wikiful_production
  encoding: unicode
  pool: 5
  timeout: 5000

